import { View, Text, ScrollView, Image } from 'react-native'
import React from 'react'



const folkloreData = [
  {
    id: 33,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Peony",
    artist: "Yun Shouping",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Animals, Deities, Heroes, Mythological Creatures, Spring and Summer Elements",
  },
    {
    id: 34,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Banzuiin Chōbei",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Cherry Blossoms (Sakura), Human Enemies",
  },
    {
    id: 35,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Benkei",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Maple Leaves (Momiji), Cherry Blossoms (Sakura), Human Enemies, Minamoto no Yoshitsune",
  },
    {
    id: 36,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Dakki no Ohyaku",
    artist: "",
    tattooBackgrounds: "Clouds",
    pairings: "Apparition (Yōkai), Demon (Oni), Severed Heads (Namakubi)",
  },
    {
    id: 37,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Daruma",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Deities, Flowers, Lucky Charms, Scattered Faces (Men Chirashi)",
  },
    {
    id: 38,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Firefighters",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Cherry Blossoms (Sakura), Dragon (Ryū), Phoenix (Hō-Ō), Tatooed Firefighters, Tattooed Water Elements",
  },
    {
    id: 39,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Fujiwara no Hidesato",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Dragon (Ryū), Flowers, Giant Centipede (Ōmukade)",
  },
    {
    id: 40,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Hakamadare and Kidōmaru",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Birds of Prey, Cherry Blossoms (Sakura), Demon (Oni), Maple Leaves (Momiji), Snake (Hebi)",
  },
    {
    id: 41,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Hanjō Danjō no Jō Arakage and the Giant Salamander",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Flowers, Giant Salamander (Ō Sanshō-Ō), Wild Beasts",
  },
    {
    id: 42,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image1.jpg"),
    title: "Hannya",
    artist: "",
    tattooBackgrounds: "Clouds",
    pairings: "Flowers, Scattered Faces (Men Chirashi), Snake (Hebi)",
  },
  {
    id: 43,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Hayakawa Ayunosuke",
    artist: "",
    tattooBackgrounds: "Clouds, Water",
    pairings: "Enemy Soldiers, Flowers",
  },
    {
    id: 44,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Higuchi Kanemitsue",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Enemy Soldiers, Flowers, Wild Beasts",
  },
    {
    id: 45,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Iga Jutarō and Takiyasha-Hime",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Apparition (Yōkai), Cherry Blossoms (Sakura), Maple Leaves (Momiji), Spider (Kumo), Toads (Gama)",
  },
    {
    id: 46,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "I No Hayata and the Nue",
    artist: "",
    tattooBackgrounds: "Clouds, Lightening",
    pairings: "Apparition (Yōkai), Cherry Blossoms (Sakura), Maple Leaves (Momiji)",
  },
    {
    id: 47,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Ishikawa Goemon",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Enemy Soliders, Flowers",
  },
    {
    id: 48,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Jigoku Dayū",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Apparitions (Yōkai), Cherry Blossoms (Sakura), Demons (Oni), Enma, Maple Leaves (Momiji), Skeletons",
  },
    {
    id: 49,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Jiraiya and Tsunade",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Enemy Soldiers, Flowers, Giant Snake (Orochi), Orochimaru, Slug (Namekuji), Toad (Gama)",
  },
    {
    id: 50,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Kamigashi-hime",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Enemy Soldiers, Flowers, Spider (Kumo), Tsuchigumo, Wild Beasts",
  },
    {
    id: 51,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Kanu Unchō",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Chōchi, Human Enemies, Ryūbi",
  },
    {
    id: 52,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image1.jpg"),
    title: "Kazusa Hirotsune",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Enemy Soldiers, Flowers, Fox (Kitsune), Nine-Tailed Fox (Kyūbi no Kitsune)",
  },
  {
    id: 53,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Kintarō",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Bear (Kuma), Boar (Inoshishi), Carp (Koi), Cherry Blossoms (Sakura), Maple Leaves (Mimiji), Snake (Hebi)",
  },
    {
    id: 54,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Kiyohime",
    artist: "",
    tattooBackgrounds: "Clouds, Water",
    pairings: "Cherry Blossoms (Sakura), Dragon (Ryū), Snake (Hebi)",
  },
    {
    id: 55,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Minamoto no Tsunetomo",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Dragon (Ryū), Enemy Soldiers, Flowers, Wild Beasts",
  },
    {
    id: 56,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Minamoto no Yorimitsu",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Apparition (Yōkai), Flowers, Four Heavenly Kings (Shi Ten-Ō), Shuten Dōji, Tsuchigumo",
  },
    {
    id: 57,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Minamoto no Yoshitsune",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Enemy Soldiers, Flowers, Wild Beasts",
  },
    {
    id: 58,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Miyamoto Musashi",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Apparition (Yōkai), Demon (Oni), Enemy Soldiers, Flowers, Wild Beasts",
  },
    {
    id: 59,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Momotarō",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Demon (Oni), Dog (Inu), Flowers, Monkey (Saru), Pheasant (Kiji), Peach (Momo)",
  },
    {
    id: 60,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Mongaku",
    artist: "",
    tattooBackgrounds: "Water",
    pairings: "Fudō Myo-Ō, Kongara Dōji and Seitaka Dōji",
  },
    {
    id: 61,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Onibaba",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Victims",
  },
    {
    id: 62,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image1.jpg"),
    title: "Oniwakamaru",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Carp (Koi), Flowers, Human Enemies",
  },
  {
    id: 63,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Ryū-Ō Tarō",
    artist: "",
    tattooBackgrounds: "Clouds",
    pairings: "Dragon (Ryū)",
  },
    {
    id: 64,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Saginoike Heikurō",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Human Enemies, Severed Heads (Namakubi), Snake (Hebi), Wild Beasts",
  },
    {
    id: 65,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Satō Masakiyo",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Apparation (Yōkai), Enemy Soldiers, Flowers, Wild Beasts",
  },
    {
    id: 66,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Shimose Kaga",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Enemy Soldiers, Flowers, Giant Snake (Orochi)",
  },
    {
    id: 67,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Shoki",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Demons (Oni), Flowers, Tiger (Tora)",
  },
    {
    id: 68,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Son Goku",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Chohakkai, Demons (Oni), Dragon (Ryū), Flowers, Genjō Sanzō, Monkeys, Sa Gojo",
  },
    {
    id: 69,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Taira no Tomomori",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Enemy Soldiers, Flowers, Heikegani, Sea Creatures",
  },
    {
    id: 70,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Tamatori-hime",
    artist: "",
    tattooBackgrounds: "Water",
    pairings: "Dragon (Ryū), Sea Creatures",
  },
    {
    id: 71,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Tenjik Tokubei",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Apparition (Yōkai), Snake (Hebi), Spider (Toma), Toads (Gama)",
  },
    {
    id: 72,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image1.jpg"),
    title: "Toki Daishirō Motosada",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Amida Buddha (Amida Hotoke), Apparition (Yōkai), Demon (Oni), Flowers, Ma-Ō, Ni-Ō",
  },
  {
    id: 73,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Tomoe Gozen",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Enemy Soldiers, Flowers, Horse",
  },
    {
    id: 74,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Waiso Saburō",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Bear (Kuma), Boar (Inoshishi), Giant Snake (Orochi), Minamoto no Yoshitsune, Wild Beasts",
  },
      {
    id: 75,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Watanabe no Tsuna",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Apparition (Yōkai), Demon (Oni), Ibaraki-dōji, Snake (Hebi), Spider (Toma), Tsuchigumo",
  },
  
]
const Folklore = () => {
  return (
    <ScrollView>
      {folkloreData.map((fauna) => (
        <View key={Folklore.id} style={{ margin: 10, alignItems: 'center' }}>
          <Image source={Folklore.imageUri} style={{ width: 100, height: 100 }} />
          <Text style={{ fontWeight: 'bold' }}>{Folklore.title}</Text>
          <Text>Artist: {Folklore.artist}</Text>
          <Text>Tattoo Backgrounds: {Folklore.tattooBackgrounds}</Text>
          <Text>Pairings: {Folklore.pairings}</Text>
        </View>
      ))}
    </ScrollView>
  );
};

export default Folklore