const imageData = [
  {
    id: 1,
    category: "Deities",
    imageUri: require("../assets/deities/Benzaiten.jpeg"),
    title: "Benzaiten",
    artist: "Aoigaoka Keisei",
    tattooBackgrounds: "Clouds, Water",
    pairings: "Dragon (Ryū), Lucky Charms, Seven Lucky Gods (Shichi Fuku Jin)", 
  },
  {
    id: 2,
    category: "Deities",
    imageUri: require("../assets/deities/Bishamonten.jpeg"),
    title: "Bishamonten",
    artist: "Unknown",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Dragon (Ryū), Oni, Seven Lucky Gods (Shichi Fuku Jin)",

  },
    {
    id: 3,
    category: "Deities",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Daiitoku Myo-Ō",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Standalone",
  },
    {
    id: 4,
    category: "Deities",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Daikokuten",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Ebisu, Flowers, Seven Lucky Gods (Shichi Fuku Jin)",
  },
    {
    id: 5,
    category: "Deities",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Dainichi Nyorai",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Flowers, Lotus (Renge)",
  },
    {
    id: 6,
    category: "Deities",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Dakiniten",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Flowers, Fox (Kitsune)",
  },
    {
    id: 7,
    category: "Deities",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Ebisu",
    artist: "",
    tattooBackgrounds: "Clouds, Water",
    pairings: "Flowers, Lucky Charms, Sea Bream (Taj), Seven Lucky Gods (Shichi Fuku Jin)",
  },
    {
    id: 8,
    category: "Deities",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Enma",
    artist: "",
    tattooBackgrounds: "Clouds, Fire, Stone",
    pairings: "Apparition (Yokai), Demons (Oni)",
  },
    {
    id: 9,
    category: "Deities",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Fudō Myo-Ō",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Dragon (Ryū), Lotus (Renge), Kongara Dōji, Seitaka Dōji, Phoenix-Shaped Flame",
  },
    {
    id: 10,
    category: "Deities",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Fūjin and Raijin",
    artist: "",
    tattooBackgrounds: "Clouds, Lightening, Water",
    pairings: "Dragon (Ryū)",
  },
    {
    id: 11,
    category: "Deities",
    // imageUri: require("./assets/category1/image1.jpg"),
    title: "Hotei",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Flowers, Seven Lucky Gods (Schichi Fuku Jin)",
  },
  {
    id: 12,
    category: "Deities",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Kannon",
    artist: "",
    tattooBackgrounds: "Clouds, Water",
    pairings: "Carp (Koi), Dragon (Ryū), Flowers, Lotus (Renge)",
  },
    {
    id: 13,
    category: "Deities",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Ni-Ō",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Buddhist Deities and Figures, Demons (Oni), Flowers",
  },
    {
    id: 14,
    category: "Deities",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Seven Lucky Gods",
    artist: "",
    tattooBackgrounds: "Clouds, Water, Stone",
    pairings: "Standalone",
  },
    {
    id: 15,
    category: "Deities",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Susanō",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Flowers, Inada Hime, Shintō Deities, Yamata no Orochi",
  },
    {
    id: 16,
    category: "Deities",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Tennyo",
    artist: "",
    tattooBackgrounds: "Clouds, Water, Stone",
    pairings: "Buddhist Deities, Flowers",
  },
    {
    id: 17,
    category: "Deities",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Oanamuchi no Mikoto",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Flowers, Wild Beasts",
  },
    {
    id: 18,
    category: "Fauna",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Carp",
    artist: "",
    tattooBackgrounds: "Water",
    pairings: "Dragon (Ryū), Flowers, Goldfish (Kingyo)",
  },
  //   {
  //   id: 19,
  //   category: "Fauna",
  //   // imageUri: require("./assets/category1/image2.jpg"),
  //   title: "",
  //   artist: "",
  //   tattooBackgrounds: "",
  //   pairings: "",
  // },
    {
    id: 20,
    category: "Fauna",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Crane",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Flowers, Lucky Charms",
  },
    {
    id: 21,
    category: "Fauna",
    // imageUri: require("./assets/category1/image1.jpg"),
    title: "Fox",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Dakiniten, Deities, Flowers, Inari (Inari Ōkami), Lucky Charms",
  },
  {
    id: 23,
    category: "Fauna",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Goldfish",
    artist: "",
    tattooBackgrounds: "Water",
    pairings: "Carp (Koi), Flowers, Freshwater Elements, Lucky Charms",
  },
    {
    id: 24,
    category: "Fauna",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Hawk",
    artist: "",
    tattooBackgrounds: "Clouds",
    pairings: "Camellias (Tsubaki), Flowers, Pine Trees (Matsu), Snake (Hebi), Warriors",
  },
    {
    id: 25,
    category: "Fauna",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Snake",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: " Flowers, Hakamadare, Hannya, Kintarō, Orochimaru, Saginoike Heikurō",
    note: "Snakes can be paired with many elements beyond the brief listing above."
  },
    {
    id: 26,
    category: "Flora",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Tiger",
    artist: "",
    tattooBackgrounds: "Clouds, Lightening, Stone, Water",
    pairings: "Bamboo (Take), Demons (Oni), Dragon (Ryū), Flowers, Gyōja Bushō, Shoki",
  },
    {
    id: 27,
    category: "Flora",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Bamboo",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Birds, Chinese Elements, Shōchikubai, Tiger (Tora), Warriors",
  },
    {
    id: 28,
    category: "Flora",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Cherry Blossoms",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Spring Elements, Elements associated with mortality",
    note: "Cherry Blossoms can be paired with many elements beyond the brief listing above."
  },
    {
    id: 29,
    category: "Flora",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Chrysanthemum",
    artist: "",
    tattooBackgrounds: "Clouds, Water",
    pairings: "Dragon (Ryū), Kirin, Phoenix (Hō-Ō)",
    note: "Chrysanthemum can be paired with many elements beyond the brief listing above."
  },
    {
    id: 30,
    category: "Flora",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Lotus",
    artist: "",
    tattooBackgrounds: "Clouds, Water",
    pairings: "Buddhist Deities and Elements",
  },
    {
    id: 31,
    category: "Flora",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Maple Leaves",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Autumn Elements",
    note: "Maple Leaves can be paired with many elements beyond the brief listing above."
  },
    {
    id: 32,
    category: "Flora",
    // imageUri: require("./assets/category1/image1.jpg"),
    title: "Peach",
    artist: "",
    tattooBackgrounds: "Clouds, Water",
    pairings: "Momotarō, Spring and Summer Elements",
  },
  {
    id: 33,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Peony",
    artist: "Yun Shouping",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Animals, Deities, Heroes, Mythological Creatures, Spring and Summer Elements",
  },
    {
    id: 34,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Banzuiin Chōbei",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Cherry Blossoms (Sakura), Human Enemies",
  },
    {
    id: 35,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Benkei",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Maple Leaves (Momiji), Cherry Blossoms (Sakura), Human Enemies, Minamoto no Yoshitsune",
  },
    {
    id: 36,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Dakki no Ohyaku",
    artist: "",
    tattooBackgrounds: "Clouds",
    pairings: "Apparition (Yōkai), Demon (Oni), Severed Heads (Namakubi)",
  },
    {
    id: 37,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Daruma",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Deities, Flowers, Lucky Charms, Scattered Faces (Men Chirashi)",
  },
    {
    id: 38,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Firefighters",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Cherry Blossoms (Sakura), Dragon (Ryū), Phoenix (Hō-Ō), Tatooed Firefighters, Tattooed Water Elements",
  },
    {
    id: 39,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Fujiwara no Hidesato",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Dragon (Ryū), Flowers, Giant Centipede (Ōmukade)",
  },
    {
    id: 40,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Hakamadare and Kidōmaru",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Birds of Prey, Cherry Blossoms (Sakura), Demon (Oni), Maple Leaves (Momiji), Snake (Hebi)",
  },
    {
    id: 41,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Hanjō Danjō no Jō Arakage and the Giant Salamander",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Flowers, Giant Salamander (Ō Sanshō-Ō), Wild Beasts",
  },
    {
    id: 42,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image1.jpg"),
    title: "Hannya",
    artist: "",
    tattooBackgrounds: "Clouds",
    pairings: "Flowers, Scattered Faces (Men Chirashi), Snake (Hebi)",
  },
  {
    id: 43,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Hayakawa Ayunosuke",
    artist: "",
    tattooBackgrounds: "Clouds, Water",
    pairings: "Enemy Soldiers, Flowers",
  },
    {
    id: 44,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Higuchi Kanemitsue",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Enemy Soldiers, Flowers, Wild Beasts",
  },
    {
    id: 45,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Iga Jutarō and Takiyasha-Hime",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Apparition (Yōkai), Cherry Blossoms (Sakura), Maple Leaves (Momiji), Spider (Kumo), Toads (Gama)",
  },
    {
    id: 46,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "I No Hayata and the Nue",
    artist: "",
    tattooBackgrounds: "Clouds, Lightening",
    pairings: "Apparition (Yōkai), Cherry Blossoms (Sakura), Maple Leaves (Momiji)",
  },
    {
    id: 47,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Ishikawa Goemon",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Enemy Soliders, Flowers",
  },
    {
    id: 48,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Jigoku Dayū",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Apparitions (Yōkai), Cherry Blossoms (Sakura), Demons (Oni), Enma, Maple Leaves (Momiji), Skeletons",
  },
    {
    id: 49,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Jiraiya and Tsunade",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Enemy Soldiers, Flowers, Giant Snake (Orochi), Orochimaru, Slug (Namekuji), Toad (Gama)",
  },
    {
    id: 50,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Kamigashi-hime",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Enemy Soldiers, Flowers, Spider (Kumo), Tsuchigumo, Wild Beasts",
  },
    {
    id: 51,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Kanu Unchō",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Chōchi, Human Enemies, Ryūbi",
  },
    {
    id: 52,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image1.jpg"),
    title: "Kazusa Hirotsune",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Enemy Soldiers, Flowers, Fox (Kitsune), Nine-Tailed Fox (Kyūbi no Kitsune)",
  },
  {
    id: 53,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Kintarō",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Bear (Kuma), Boar (Inoshishi), Carp (Koi), Cherry Blossoms (Sakura), Maple Leaves (Mimiji), Snake (Hebi)",
  },
    {
    id: 54,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Kiyohime",
    artist: "",
    tattooBackgrounds: "Clouds, Water",
    pairings: "Cherry Blossoms (Sakura), Dragon (Ryū), Snake (Hebi)",
  },
    {
    id: 55,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Minamoto no Tsunetomo",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Dragon (Ryū), Enemy Soldiers, Flowers, Wild Beasts",
  },
    {
    id: 56,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Minamoto no Yorimitsu",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Apparition (Yōkai), Flowers, Four Heavenly Kings (Shi Ten-Ō), Shuten Dōji, Tsuchigumo",
  },
    {
    id: 57,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Minamoto no Yoshitsune",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Enemy Soldiers, Flowers, Wild Beasts",
  },
    {
    id: 58,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Miyamoto Musashi",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Apparition (Yōkai), Demon (Oni), Enemy Soldiers, Flowers, Wild Beasts",
  },
    {
    id: 59,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Momotarō",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Demon (Oni), Dog (Inu), Flowers, Monkey (Saru), Pheasant (Kiji), Peach (Momo)",
  },
    {
    id: 60,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Mongaku",
    artist: "",
    tattooBackgrounds: "Water",
    pairings: "Fudō Myo-Ō, Kongara Dōji and Seitaka Dōji",
  },
    {
    id: 61,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Onibaba",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Victims",
  },
    {
    id: 62,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image1.jpg"),
    title: "Oniwakamaru",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Carp (Koi), Flowers, Human Enemies",
  },
  {
    id: 63,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Ryū-Ō Tarō",
    artist: "",
    tattooBackgrounds: "Clouds",
    pairings: "Dragon (Ryū)",
  },
    {
    id: 64,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Saginoike Heikurō",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Human Enemies, Severed Heads (Namakubi), Snake (Hebi), Wild Beasts",
  },
    {
    id: 65,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Satō Masakiyo",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Apparation (Yōkai), Enemy Soldiers, Flowers, Wild Beasts",
  },
    {
    id: 66,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Shimose Kaga",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Enemy Soldiers, Flowers, Giant Snake (Orochi)",
  },
    {
    id: 67,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Shoki",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Demons (Oni), Flowers, Tiger (Tora)",
  },
    {
    id: 68,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Son Goku",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Chohakkai, Demons (Oni), Dragon (Ryū), Flowers, Genjō Sanzō, Monkeys, Sa Gojo",
  },
    {
    id: 69,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Taira no Tomomori",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Enemy Soldiers, Flowers, Heikegani, Sea Creatures",
  },
    {
    id: 70,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Tamatori-hime",
    artist: "",
    tattooBackgrounds: "Water",
    pairings: "Dragon (Ryū), Sea Creatures",
  },
    {
    id: 71,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Tenjik Tokubei",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Apparition (Yōkai), Snake (Hebi), Spider (Toma), Toads (Gama)",
  },
    {
    id: 72,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image1.jpg"),
    title: "Toki Daishirō Motosada",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Amida Buddha (Amida Hotoke), Apparition (Yōkai), Demon (Oni), Flowers, Ma-Ō, Ni-Ō",
  },
  {
    id: 73,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Tomoe Gozen",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Enemy Soldiers, Flowers, Horse",
  },
    {
    id: 74,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Waiso Saburō",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Bear (Kuma), Boar (Inoshishi), Giant Snake (Orochi), Minamoto no Yoshitsune, Wild Beasts",
  },
      {
    id: 75,
    category: "Folklore/History",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Watanabe no Tsuna",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Apparition (Yōkai), Demon (Oni), Ibaraki-dōji, Snake (Hebi), Spider (Toma), Tsuchigumo",
  },
  
    {
    id: 76,
    category: "Suikoden",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Gyōja Bushō",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Enemy Soldiers, Flowers, Tiger (Tora)",
  },
    {
    id: 77,
    category: "Suikoden",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Kanchi Kotsuritsu Shuki",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Enemy Soldiers, Flowers",
  },
    {
    id: 78,
    category: "Suikoden",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Kaoshō Rochisin",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Enemy Soldiers, Flowers, Nine-Deragons-Crested Shishin (Kumonryū Shishin/ Panther Head Rinchu/ Hyoshito Rinchu), Tiger-Slaying General Richū (Dakoshō Richū)",
  },
    {
    id: 79,
    category: "Suikoden",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Konkoryū Rishun",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Enemy Soldiers, Flowers",
  },
    {
    id: 80,
    category: "Suikoden",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Ko Sanjō",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Enemy Soldiers, Flowers",
  },
    {
    id: 81,
    category: "Suikoden",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Kumonryū Shishin",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Dragon (Ryū), Enemy Soldiers",
  },
    {
    id: 82,
    category: "Suikoden",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Rori Hakuchō Chōjun",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Enemy Soldiers, Flowers",
  },
    {
    id: 83,
    category: "Suikoden",
    // imageUri: require("./assets/category1/image1.jpg"),
    title: "Rōshi Ensei",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Enemy Soldiers, Flowers",
  },
  {
    id: 84,
    category: "Suikoden",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Saienshi Chōsei",
    artist: "",
    tattooBackgrounds: "Clouds, stone, Water",
    pairings: "Cherry Blossoms (Sakura), Maple Leaves (Momiji)",
  },
    {
    id: 85,
    category: "Suikoden",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Senkaji Chō-Ō",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Enemy Soldiers, Flowers",
  },
    {
    id: 86,
    category: "Suikoden",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Tanmei Jirō Gen Shōgo",
    artist: "",
    tattooBackgrounds: "Water",
    pairings: "Carp (Koi), Enemy Soldoiers",
  },
    {
    id: 87,
    category: "Supernatural",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Baku",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Apparition (Yōkai), Demon (Oni), Flowers, Lucky Charms",
  },
    {
    id: 88,
    category: "Supernatural",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Dragon",
    artist: "",
    tattooBackgrounds: "Clouds, Water",
    pairings: "Buddhist Deities, Carp (Koi), Dragon (Ryū), Four Symbols (Shi Shō), Phoenix (Hō-Ō), Tiger (Tora)",
    note: "Dragons can be paired with many elements beyond the brief listing above."
  },
    {
    id: 89,
    category: "Supernatural",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Dragon and Tiger",
    artist: "",
    tattooBackgrounds: "Clouds, Lightening, Stone, Water",
    pairings: "Flowers, Standalone",
  },
    {
    id: 90,
    category: "Supernatural",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Hakutaku",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Flowers, Kirin",
  },
    {
    id: 91,
    category: "Supernatural",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Kappa",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Apparition (Yōkai), Flowers, Heroes",
  },
    {
    id: 92,
    category: "Supernatural",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Karajishi",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Buddhist Deities and Elements, Koma Inu, Peony (Botan)",
  },
    {
    id: 93,
    category: "Supernatural",
    // imageUri: require("./assets/category1/image1.jpg"),
    title: "Kirin",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Flowers, Phoenix (Hō-Ō)",
  },
  {
    id: 94,
    category: "Supernatural",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Namakubi",
    artist: "",
    tattooBackgrounds: "Clouds, Stonem, Water",
    pairings: "Apparition (Yōkai), Demon (Oni), Flowers, Saginoike Heikurō, Warriors",
  },
    {
    id: 95,
    category: "Supernatural",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Nekomata",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Apparition (Yōkai), Cherry Blossoms (Sakura), Maple Leaves (Momiji), Severed Heads (Namakubi)",
  },
    {
    id: 96,
    category: "Supernatural",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Ōmukade",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Dragon (Ryū), Fujiwara no Hidesato",
  },
    {
    id: 97,
    category: "Supernatural",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Phoenix",
    artist: "",
    tattooBackgrounds: "Clouds",
    pairings: "Buddhist Deities, Dragon (Ryū), Flowers, Kirin",
  },
    {
    id: 98,
    category: "Supernatural",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Rokuro Kubi",
    artist: "",
    tattooBackgrounds: "Clouds",
    pairings: "Apparition (Yōkai), Cherry Blossoms (Sakura), Severed Heads (Namakubi)",
  },
    {
    id: 99,
    category: "Supernatural",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Sōjōbō",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Flowers, Tengu, Ushiwakamaru",
  },
    {
    id: 100,
    category: "Supernatural",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Sumizome",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Cherry Blossoms (Sakura)",
  },
      {
    id: 101,
    category: "Supernatural",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Tengu",
    artist: "",
    tattooBackgrounds: "Clouds, Stone, Water",
    pairings: "Dragon (Ryū), Flowers, Kintarō, Minamoto no Yoshitsune, Sōjōbō, Scattered Faces (Men Chirashi)",
  },
      {
    id: 102,
    category: "Supernatural",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Tsuchigumo",
    artist: "",
    tattooBackgrounds: "Clouds, Stone",
    pairings: "Minamoto no Yorimitsu, Spiders (Kumo), Watanabe no Tsuna",
  },
      {
    id: 103,
    category: "Supernatural",
    // imageUri: require("./assets/category1/image2.jpg"),
    title: "Yatagarasu",
    artist: "",
    tattooBackgrounds: "Clouds",
    pairings: "Amaterasu, Jimmu (Jinmu Ten-Ō), Warriors",
  },


  
];

export default imageData;
